/*
 * flash.h
 *
 *  Created on: 2023年11月24日
 *      Author: xinhao
 */

#ifndef FLASH_H_
#define FLASH_H_

#include "reg.h"

#define FLASH_OSPI_CFG_ADDR  QSPI_CFG_BASE


#define FLASH_OSPI_CONFIG     REG32(FLASH_OSPI_CFG_ADDR + 0x00)
#define FLASH_OSPI_DRIR       REG32(FLASH_OSPI_CFG_ADDR + 0x04)
#define FLASH_OSPI_DWIR       REG32(FLASH_OSPI_CFG_ADDR + 0x08)
#define FLASH_OSPI_DDR        REG32(FLASH_OSPI_CFG_ADDR + 0x0C)
#define FLASH_OSPI_RDCR       REG32(FLASH_OSPI_CFG_ADDR + 0x10)
#define FLASH_OSPI_DSR        REG32(FLASH_OSPI_CFG_ADDR + 0x14)
#define FLASH_OSPI_SPR        REG32(FLASH_OSPI_CFG_ADDR + 0x18)
#define FLASH_OSPI_IAATR      REG32(FLASH_OSPI_CFG_ADDR + 0x1C)
#define FLASH_OSPI_DPR        REG32(FLASH_OSPI_CFG_ADDR + 0x20)
#define FLASH_OSPI_RAR        REG32(FLASH_OSPI_CFG_ADDR + 0x24)
#define FLASH_OSPI_MBR        REG32(FLASH_OSPI_CFG_ADDR + 0x28)
#define FLASH_OSPI_SFLR       REG32(FLASH_OSPI_CFG_ADDR + 0x2C)
#define FLASH_OSPI_TTR        REG32(FLASH_OSPI_CFG_ADDR + 0x30)
#define FLASH_OSPI_RTR        REG32(FLASH_OSPI_CFG_ADDR + 0x34)
#define FLASH_OSPI_WCCR       REG32(FLASH_OSPI_CFG_ADDR + 0x38)
#define FLASH_OSPI_PER        REG32(FLASH_OSPI_CFG_ADDR + 0x3C)
#define FLASH_OSPI_ISR        REG32(FLASH_OSPI_CFG_ADDR + 0x40)
#define FLASH_OSPI_IMR        REG32(FLASH_OSPI_CFG_ADDR + 0x44)
#define FLASH_OSPI_LWPR       REG32(FLASH_OSPI_CFG_ADDR + 0x50)
#define FLASH_OSPI_UWPR       REG32(FLASH_OSPI_CFG_ADDR + 0x54)
#define FLASH_OSPI_WPR        REG32(FLASH_OSPI_CFG_ADDR + 0x58)
#define FLASH_OSPI_IRTR       REG32(FLASH_OSPI_CFG_ADDR + 0x60)
#define FLASH_OSPI_IRTWR      REG32(FLASH_OSPI_CFG_ADDR + 0x64)
#define FLASH_OSPI_IRTSAR     REG32(FLASH_OSPI_CFG_ADDR + 0x68)
#define FLASH_OSPI_IRTNBR     REG32(FLASH_OSPI_CFG_ADDR + 0x6C)
#define FLASH_OSPI_IWTR       REG32(FLASH_OSPI_CFG_ADDR + 0x70)
#define FLASH_OSPI_IWTWR      REG32(FLASH_OSPI_CFG_ADDR + 0x74)
#define FLASH_OSPI_IWTSAR     REG32(FLASH_OSPI_CFG_ADDR + 0x78)
#define FLASH_OSPI_IWTNBR     REG32(FLASH_OSPI_CFG_ADDR + 0x7C)
#define FLASH_OSPI_IATARR     REG32(FLASH_OSPI_CFG_ADDR + 0x80)
#define FLASH_OSPI_FCCMR      REG32(FLASH_OSPI_CFG_ADDR + 0x8C)
#define FLASH_OSPI_FCCR       REG32(FLASH_OSPI_CFG_ADDR + 0x90)
#define FLASH_OSPI_FCAR       REG32(FLASH_OSPI_CFG_ADDR + 0x94)
#define FLASH_OSPI_FCRDRL     REG32(FLASH_OSPI_CFG_ADDR + 0xA0)
#define FLASH_OSPI_FCRDRU     REG32(FLASH_OSPI_CFG_ADDR + 0xA4)
#define FLASH_OSPI_FCWDRL     REG32(FLASH_OSPI_CFG_ADDR + 0xA8)
#define FLASH_OSPI_FCWDRU     REG32(FLASH_OSPI_CFG_ADDR + 0xAC)
#define FLASH_OSPI_PFSR       REG32(FLASH_OSPI_CFG_ADDR + 0xB0)
#define FLASH_OSPI_PCR        REG32(FLASH_OSPI_CFG_ADDR + 0xB4)
#define FLASH_OSPI_PDMC       REG32(FLASH_OSPI_CFG_ADDR + 0xB8)
#define FLASH_OSPI_DORL       REG32(FLASH_OSPI_CFG_ADDR + 0xBC)
#define FLASH_OSPI_DORU       REG32(FLASH_OSPI_CFG_ADDR + 0xC0)
#define FLASH_OSPI_OERL       REG32(FLASH_OSPI_CFG_ADDR + 0xE0)
#define FLASH_OSPI_OERU       REG32(FLASH_OSPI_CFG_ADDR + 0xE4)
#define FLASH_OSPI_MIR        REG32(FLASH_OSPI_CFG_ADDR + 0xFC)

int debug_test_flash(void);

#endif /* FLASH_H_ */
