name: Sync to Gitee

on:
  push:
    branches: [main, release/*]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Gitee
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: "git@gitee.com:xingxinonline/s300-ai-vision-suite.git" # 假设 Gitee 也有相同的组织和仓库名，请根据实际情况修改
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          ARGS: "--tags --force"
